In [1]:
#imporint warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
#reading in the cleaned retail dataset
data= pd.read_excel("Retail_dataset_cleaned.xlsx")
data.head()

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Unnamed: 0,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date,order_item_id,product_id,...,product_length_cm,product_height_cm,product_width_cm,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,19,8,13,3149,sao paulo,SP,1,credit_card,1,18.12
1,1,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,19,8,13,3149,sao paulo,SP,3,voucher,1,2.00
2,2,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,19,8,13,3149,sao paulo,SP,2,voucher,1,18.59
3,3,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,19,13,19,47813,barreiras,BA,1,wallet,1,141.46
4,4,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,24,19,21,75265,vianopolis,GO,1,credit_card,3,179.12

In [4]:
#checking the shape
data.shape

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(115268, 25)

In [5]:
#checking the columns
data.columns

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Index(['Unnamed: 0', 'order_id', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_timestamp', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'price', 'shipping_charges',
       'product_category_name', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [40]:
#creating the basket
basket= data.groupby(["order_id", "product_category_name"])["order_item_id"].sum().unstack().reset_index().fillna(0).set_index("order_id")
basket.head()

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

product_category_name,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
00018f77f2f0320c557190d7a144bdd3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
000229ec398224ef6ca0657da4fc703e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
00024acbcdf0a6daa1e931b038114c75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
00042b26cf59d7ce69dfabb4e55b4fd9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [42]:
#setting everything lesser than 0 to 0 and greater than 1 to 1
def encoding_units(x):
    if x<=0:
        return 0
    else:
        return 1

basket= basket.applymap(encoding_units)
basket.head()

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

product_category_name,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
00018f77f2f0320c557190d7a144bdd3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
000229ec398224ef6ca0657da4fc703e,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
00024acbcdf0a6daa1e931b038114c75,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
00042b26cf59d7ce69dfabb4e55b4fd9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [51]:
# Filtering the Basket with the sum of values having >=2 to find itemsets with groups of equal to or more than 2

basket_filter = basket[(basket > 0).sum(axis=1) >=2]
basket_filter

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

product_category_name,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
order_id,,,,,,,,,,,,,,,,,,,,,
00337fe25a3780b3424d9ad7c5a4b35e,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
00946f674d880be1f188abc10ad7cf46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
00bcee890eba57a9767c7b5ca12d3a1b,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
01144cadcf64b6427f0a6580a3033220,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
013a98b3a668bcef05b98898177f6923,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ff632bc583a94f23c59db4cbaa0ba2ab,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
ffa466d3e55f98477b7e0da764df3c6c,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
ffb9a9cd00c74c11c24aa30b3d78e03b,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
ffc16cecff8dc037f60458f28d1c1ba5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
ffd543c2b60842e148a86870dc60e212,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [58]:
#now applying apriori algorithm to find frequent datasets
frequent_itemsets = apriori(basket_filter, min_support=0.05,use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)
frequent_itemsets["Length"] = frequent_itemsets['itemsets'].apply(lambda x:len(x))

frequent_itemsets

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
C:\Users\user\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                       itemsets  Length
0   0.971139                         (toys)       1
1   0.230889               (bed_bath_table)       1
2   0.226989         (toys, bed_bath_table)       2
3   0.127145              (furniture_decor)       1
4   0.119345        (toys, furniture_decor)       2
5   0.084243        (computers_accessories)       1
6   0.080343  (toys, computers_accessories)       2
7   0.065523                (health_beauty)       1
8   0.062402          (toys, health_beauty)       2
9   0.058502                (watches_gifts)       1
10  0.056942          (toys, watches_gifts)       2
11  0.054602               (sports_leisure)       1
12  0.053822                   (housewares)       1

In [61]:
rules = association_rules(frequent_itemsets, metric='lift',min_threshold = 0.8).sort_values('lift', ascending=False).reset_index(drop=True)
rules

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(toys),(bed_bath_table),0.971139,0.230889,0.226989,0.233735,1.012325,0.002764,1.003714
1,(bed_bath_table),(toys),0.230889,0.971139,0.226989,0.983108,1.012325,0.002764,1.708580
2,(toys),(watches_gifts),0.971139,0.058502,0.056942,0.058635,1.002260,0.000128,1.000140
3,(watches_gifts),(toys),0.058502,0.971139,0.056942,0.973333,1.002260,0.000128,1.082293
4,(toys),(computers_accessories),0.971139,0.084243,0.080343,0.082731,0.982047,-0.001469,0.998351
5,(computers_accessories),(toys),0.084243,0.971139,0.080343,0.953704,0.982047,-0.001469,0.623401
6,(toys),(health_beauty),0.971139,0.065523,0.062402,0.064257,0.980685,-0.001229,0.998647
7,(health_beauty),(toys),0.065523,0.971139,0.062402,0.952381,0.980685,-0.001229,0.606084
8,(toys),(furniture_decor),0.971139,0.127145,0.119345,0.122892,0.966546,-0.004131,0.995151
9,(furniture_decor),(toys),0.127145,0.971139,0.119345,0.938650,0.966546,-0.004131,0.470437

### Observations

**1. 97% of customers buying toys are likely to but bed_bath_table**

**2. 97% of customers buying toys are likely to buy watches_gifts**

**3. 97% of customers buying toys are likely to buy computer accessories**

**4. 97% of customers buying toys are likely to buy health_beauty**

**5. 97% of customers buying toys are likely to buy furniture_decor**

**So these are the top 5 frequent itemsets in groups of two**

In [66]:
# Filtering the Basket with the sum of values having >=3 to find itemsets with groups of equal to or more than 3

basket_filter_2 = basket[(basket > 0).sum(axis=1) >=3]
basket_filter_2.head()

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

product_category_name,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
order_id,,,,,,,,,,,,,,,,,,,,,
0a77b770428bccbea7f9dbf8aec5d6ae,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1c4a92d82c1b0dec18bef12da3fa7756,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
43443d5fff4b94d98df1ad41af13d302,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
5337d26d14027f547caacb7fee230f81,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
91be51c856a90d7efe86cf9d082d6ae3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [67]:
#now applying apriori algorithm to find frequent datasets
frequent_itemsets = apriori(basket_filter_2, min_support=0.05,use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)
frequent_itemsets["Length"] = frequent_itemsets['itemsets'].apply(lambda x:len(x))

frequent_itemsets

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
C:\Users\user\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                                          itemsets  Length
0       1.0                                            (toys)       1
1       0.5                                  (bed_bath_table)       1
2       0.5                            (toys, bed_bath_table)       2
3       0.4                                 (furniture_decor)       1
4       0.4                           (toys, furniture_decor)       2
5       0.2                                    (garden_tools)       1
6       0.2                           (computers_accessories)       1
7       0.2                              (toys, garden_tools)       2
8       0.2                     (toys, computers_accessories)       2
9       0.2           (toys, furniture_decor, bed_bath_table)       3
10      0.2                 (furniture_decor, bed_bath_table)       2
11      0.1                (toys, housewares, bed_bath_table)       3
12      0.1              (toys, electronics, furniture_decor)       3
13      0.1                   (furniture_decor, garden_tools)       2
14      0.1             (toys, health_beauty, bed_bath_table)       3
15      0.1  (toys, home_construction, computers_accessories)       3
16      0.1                                 (telephony, toys)       2
17      0.1          (toys, bed_bath_table, office_furniture)       3
18      0.1                          (toys, office_furniture)       2
19      0.1                                (toys, housewares)       2
20      0.1                         (toys, home_construction)       2
21      0.1                             (toys, health_beauty)       2
22      0.1                     (telephony, cine_photo, toys)       3
23      0.1       (toys, garden_tools, computers_accessories)       3
24      0.1        (home_construction, computers_accessories)       2
25      0.1                               (toys, electronics)       2
26      0.1                    (furniture_decor, electronics)       2
27      0.1                                      (cine_photo)       1
28      0.1             (garden_tools, computers_accessories)       2
29      0.1                                (toys, cine_photo)       2
30      0.1                           (telephony, cine_photo)       2
31      0.1                (bed_bath_table, office_furniture)       2
32      0.1                      (housewares, bed_bath_table)       2
33      0.1                   (health_beauty, bed_bath_table)       2
34      0.1                                       (telephony)       1
35      0.1                                (office_furniture)       1
36      0.1                                      (housewares)       1
37      0.1                               (home_construction)       1
38      0.1                                   (health_beauty)       1
39      0.1                                     (electronics)       1
40      0.1             (toys, garden_tools, furniture_decor)       3

In [71]:
rules_2 = association_rules(frequent_itemsets, metric='lift',min_threshold = 0.8).sort_values('lift', ascending=False).reset_index(drop=True)
rules_2.head(20)

C:\Users\user\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(telephony, toys)",(cine_photo),0.1,0.1,0.1,1.00,10.0,0.09,inf
1,(cine_photo),(telephony),0.1,0.1,0.1,1.00,10.0,0.09,inf
2,"(toys, cine_photo)",(telephony),0.1,0.1,0.1,1.00,10.0,0.09,inf
3,(telephony),"(toys, cine_photo)",0.1,0.1,0.1,1.00,10.0,0.09,inf
4,(cine_photo),"(telephony, toys)",0.1,0.1,0.1,1.00,10.0,0.09,inf
5,(telephony),(cine_photo),0.1,0.1,0.1,1.00,10.0,0.09,inf
6,(home_construction),"(toys, computers_accessories)",0.1,0.2,0.1,1.00,5.0,0.08,inf
7,(computers_accessories),(home_construction),0.2,0.1,0.1,0.50,5.0,0.08,1.8
8,"(toys, computers_accessories)",(home_construction),0.2,0.1,0.1,0.50,5.0,0.08,1.8
9,"(toys, home_construction)",(computers_accessories),0.1,0.2,0.1,1.00,5.0,0.08,inf
10,(home_construction),(computers_accessories),0.1,0.2,0.1,1.00,5.0,0.08,inf
11,(computers_accessories),"(toys, home_construction)",0.2,0.1,0.1,0.50,5.0,0.08,1.8
12,(furniture_decor),"(toys, electronics)",0.4,0.1,0.1,0.25,2.5,0.06,1.2
13,"(toys, electronics)",(furniture_decor),0.1,0.4,0.1,1.00,2.5,0.06,inf
14,(garden_tools),"(toys, computers_accessories)",0.2,0.2,0.1,0.50,2.5,0.06,1.6
15,(electronics),"(toys, furniture_decor)",0.1,0.4,0.1,1.00,2.5,0.06,inf
16,(electronics),(furniture_decor),0.1,0.4,0.1,1.00,2.5,0.06,inf
17,(garden_tools),(computers_accessories),0.2,0.2,0.1,0.50,2.5,0.06,1.6
18,"(toys, furniture_decor)",(electronics),0.4,0.1,0.1,0.25,2.5,0.06,1.2
19,(furniture_decor),(electronics),0.4,0.1,0.1,0.25,2.5,0.06,1.2

### Observations

**Based on the above output we can conclude that the top 3 itemsets in groups of three are:**

**1. telephony, toys and cine photo**

**2. home construction, toys and computer accessories**

**3. furniture decorations, toys and electronics**